name: Github package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack
      run: dotnet pack src/Fiffi/Fiffi.csproj --configuration Release -o artifacts
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: artifacts/**/*
    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
          nupkg-path:  './artifacts/**.nupkg'
          repo-owner:  'perokvist'
          gh-user:  'perokvist'
          token:  ${{ secrets.GITHUB_TOKEN }}
